import type { Resource, Lesson, Event, Track } from "@/types"

export const tracks: Track[] = [
  {
    id: "1",
    slug: "skills",
    title: "Skills",
    coverImage: "/images/track-skills.jpg",
    description: "Templates e recursos prontos para usar nos seus projetos",
  },
  {
    id: "2",
    slug: "ferramentas",
    title: "Ferramentas",
    coverImage: "/images/track-ferramentas.jpg",
    description: "Ferramentas de IA para design e produtividade",
  },
  {
    id: "3",
    slug: "claude-code-na-pratica",
    title: "Claude Code na Prática",
    coverImage: "/images/track-claude.jpg",
    description: "Aprenda a usar o Claude Code como eu uso no dia a dia",
  },
  {
    id: "4",
    slug: "lives-gravadas",
    title: "Lives Gravadas",
    coverImage: "/images/track-lives.jpg",
    description: "Todas as lives gravadas para assistir quando quiser",
  },
  {
    id: "5",
    slug: "agentes",
    title: "Agentes",
    coverImage: "/images/track-agentes.jpg",
    description: "Agentes de IA prontos para automatizar seu trabalho",
  },
  {
    id: "6",
    slug: "mapa-mental",
    title: "Mapa Mental",
    coverImage: "/images/track-mapa-mental.jpg",
    description: "Estruturas e mapas mentais para organizar seu pensamento",
  },
]

export const resources: Resource[] = [
  {
    id: "1",
    slug: "skill-video-use-editar-videos-com-claude",
    title: "Skill Vídeo Use / Editar Vídeos Com o Claude",
    description:
      "Skill completa para editar vídeos usando o Claude como co-piloto. Inclui prompts, workflow e exemplos práticos.",
    coverImage: "https://images.unsplash.com/photo-1536240478700-b869ad10e9be?w=400&q=80",
    downloadUrl: "#",
    track: ["skills"],
    tags: ["Skills"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "2",
    slug: "skill-finder-passo",
    title: "Skill Finder Passo",
    description:
      "Template de skill para encontrar o próximo passo em qualquer projeto usando IA.",
    coverImage: "/images/resource-finder.jpg",
    downloadUrl: "#",
    track: ["skills"],
    tags: ["Skills"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "3",
    slug: "skill-epic-paper",
    title: "Skill Epic Paper",
    description:
      "Conecte o Claude ao Paper Design e crie interfaces incríveis com IA. Skill completa com exemplos e prompts.",
    coverImage: "https://images.unsplash.com/photo-1617791160505-6f00504e3519?w=400&q=80",
    downloadUrl: "#",
    track: ["skills", "ai-design"],
    tags: ["Skills", "AI Design"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "4",
    slug: "design-skill-anthropics",
    title: "Design Skill | Anthropics",
    description:
      "Skill de design usando as ferramentas da Anthropic para criar projetos visuais profissionais.",
    coverImage: "/images/resource-design.jpg",
    downloadUrl: "#",
    track: ["skills", "ai-design"],
    tags: ["Skills", "AI Design"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "5",
    slug: "home-ui",
    title: "Home UI",
    description:
      "Template de home page com UI moderna criada com Claude Code e shadcn/ui.",
    coverImage: "/images/resource-home-ui.jpg",
    downloadUrl: "#",
    track: ["ai-design"],
    tags: ["AI Design"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "6",
    slug: "criando-seu-design-system",
    title: "Criando Seu Design System",
    description:
      "Guia completo para criar um design system do zero usando IA. Inclui tokens, componentes e documentação.",
    coverImage: "/images/resource-design-system.jpg",
    downloadUrl: "#",
    track: ["ai-design"],
    tags: ["AI Design"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "7",
    slug: "prompt-para-design-de-notas-claude-paper",
    title: "Prompt para Design de Notas com Claude + Paper",
    description:
      "Coleção de prompts para criar designs de notas e documentos usando Claude e Paper Design.",
    coverImage: "/images/resource-prompt.jpg",
    downloadUrl: "#",
    track: ["ai-design"],
    tags: ["AI Design"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
  {
    id: "8",
    slug: "guia-do-deploy",
    title: "Guia do Deploy",
    description:
      "Passo a passo para fazer deploy de qualquer projeto usando Vercel, GitHub e Claude Code.",
    coverImage: "/images/resource-deploy.jpg",
    downloadUrl: "#",
    track: ["skills"],
    tags: ["Skills"],
    type: "resource",
    updatedAt: "2026-04-20",
  },
]

export const lessons: Lesson[] = [
  {
    id: "1",
    slug: "aula-1-introducao-comece-por-aqui",
    title: "Aula 1: Introdução (Comece Por Aqui)",
    description:
      "Boas-vindas à biblioteca! Nesta aula você entende como tudo funciona, o que vai aprender e como aproveitar ao máximo o conteúdo.",
    coverImage: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=400&q=80",
    videoUrl: "",
    duration: "12:45",
    track: "claude-code-na-pratica",
    type: "class",
    locked: false,
    order: 1,
  },
  {
    id: "2",
    slug: "aula-2-como-eu-planejo-meus-apps",
    title: "Aula 2: Como eu planejo meus apps antes de fazer código",
    description:
      "Veja meu processo completo de planejamento antes de abrir o Claude Code. Como estruturo ideias, defino escopo e crio o briefing perfeito.",
    coverImage: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=400&q=80",
    videoUrl: "",
    duration: "28:30",
    track: "claude-code-na-pratica",
    type: "class",
    locked: true,
    order: 2,
  },
  {
    id: "3",
    slug: "aula-3-como-habitar-a-folio-ui",
    title: "Aula 3: Como habitar a Fólio UI",
    description:
      "Tutorial completo da Fólio UI — template premium que uso em todos os meus projetos. Customização, componentes e fluxo de trabalho.",
    coverImage: "/images/lesson-3.jpg",
    videoUrl: "",
    duration: "45:12",
    track: "claude-code-na-pratica",
    type: "class",
    locked: true,
    order: 3,
  },
  {
    id: "4",
    slug: "aula-4-construindo-seu-projeto-em-site-ai",
    title: "Aula 4: Construindo seu Projeto em Site AI",
    description:
      "Do zero ao deploy — construo um site completo ao vivo usando Claude Code, Next.js e Vercel. Você vê cada decisão em tempo real.",
    coverImage: "/images/lesson-4.jpg",
    videoUrl: "",
    duration: "1:02:18",
    track: "claude-code-na-pratica",
    type: "class",
    locked: true,
    order: 4,
  },
  {
    id: "5",
    slug: "aula-5-transformacoes-mockup-em-spenc",
    title: "Aula 5: Transformações — Mockup em Spenc",
    description:
      "Como transformo mockups e wireframes em código real usando o Claude Code. Processo, prompts e dicas para não perder tempo.",
    coverImage: "/images/lesson-5.jpg",
    videoUrl: "",
    duration: "38:55",
    track: "claude-code-na-pratica",
    type: "class",
    locked: true,
    order: 5,
  },
]

export const events: Event[] = [
  {
    id: "1",
    slug: "live-com-a-comunidade-tema-tbd-1",
    title: "Live com a Comunidade (Tema TBD)",
    coverImage: "/images/event-1.jpg",
    date: "2026-04-20",
    time: "19:00 às 21:00",
    type: "event",
    locked: true,
  },
  {
    id: "2",
    slug: "live-com-a-comunidade-tema-tbd-2",
    title: "Live com a Comunidade (Tema TBD)",
    coverImage: "/images/event-2.jpg",
    date: "2026-04-20",
    time: "19:00 às 21:00",
    type: "event",
    locked: true,
  },
  {
    id: "3",
    slug: "reagindo-aos-projetos-30-04",
    title: "Reagindo aos Projetos da Comunidade (30/04/26)",
    coverImage: "/images/event-react-1.jpg",
    date: "2026-04-30",
    time: "",
    type: "class",
    recordingUrl: "",
    locked: true,
  },
  {
    id: "4",
    slug: "me-pergunte-qualquer-coisa-03-05",
    title: "Me Pergunte Qualquer Coisa (03/05/26)",
    coverImage: "/images/event-qa-1.jpg",
    date: "2026-05-03",
    time: "",
    type: "class",
    recordingUrl: "",
    locked: true,
  },
]

export const currentUser = {
  name: "Gabriel",
  email: "gdealmeida629@gmail.com",
  avatarUrl: "/images/avatar.jpg",
  plan: "free" as const,
}
